### ISSUE TITLE
Add a filter for `Serotype` on the dashboard

### ISSUE THREAD

**Issue by SeanKennyNF** [serotracker/dashboard#106]
> > Feedback: Dengue by subtype, to layer infection with diff serotypes, as a possible filter

> Harriet: We've added this variable in airtable, need to add to the dashboard

Blocked by https://github.com/PathoTracker/Pathotracker/issues/105

Let's add a filter by serotype. Serotype is a list and many non-dengue studies don't have serotypes listed. I think the way the filter would work is that it would work like the `pathogen` filter where every possible value is selected at the start and then you can choose to remove some of them. Studies would stay as a part of the filter if at least one of the serotypes in their list is included in the list in the filter.

If the study doesn't have a `serotype` (most of the studies) the serotype filter shouldn't affect it at all in my opinion.

It would be neat to (and probably easy?) add this to the analysis table as well I think. We could probably copy our code for `Antibodies` and also have the pretty colours :)

**Comment by harrietware** [comment]
This all sounds great! Serotype is dengue-specific so only dengue studies will have serotypes listed :)

**Comment by EliasPinno** [comment]
look in `useArboFilters` and `useArboData` to see how it works. Dm @SeanKennyNF if you are lost.
