### ISSUE TITLE
Remove the "Arbovirus" filter from the filters on the left on the redesigned dashboard page when the map is in view.

### ISSUE THREAD

**Issue by SeanKennyNF** [serotracker/dashboard#186]
Created from https://github.com/serotracker/dashboard/pull/183#discussion_r1493831304

> So an interesting consequence of what I've done is that the pathogen filter will always be shown since I'm no longer tracking which section is in view. If removing the pathogen filter when you're looking at the map is a feature we're interested in having on the new dashboard, let's make a separate ticket for that because it's a bit more involved now.

When the map is visible, the "Arbovirus" filter on the left of the map (circled in red on the left) should disappear because it is redundant with the arbovirus checkboxes present on the right side of the map (circled in red on the right). The Arbovirus filters should be visible again once someone scrolls to a different section of the dashboard such as the table or the visualizations so it's not sufficient to just look at the url param and we need something that determines whether or not the map is in view I'd imagine.

![Screenshot from 2024-02-19 14-56-00](https://github.com/serotracker/dashboard/assets/86806388/28ee5638-cb67-44b8-9c74-ceb9afbcf07a)

**Comment by EliasPinno** [comment]
Change: now remove the legend from the map, and leave it as a pinned thing on the top of the filter bar.
