### ISSUE TITLE
Add country-level visualization of study estimates

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#214]
Both Thomas and David Buckeridge mentioned the importance of showing uncertainty around the estimates. To do this we could add a visualization that is only available if the user selects 1 pathogen and 1-2 countries (other filters continue to apply). Open to suggestions on how we prompt users that this option is available. 

The visualization would display all of the study estimates with 95% confidence intervals in a given country for a given pathogen, with side-by-side graphs if >1 country is selected (example below). For the 95% confidence intervals, use the new variables in AT "Seroprevalence 95% CI Lower (formula)" and "Seroprevalence 95% CI Upper (formula)" - these are calculated by us, not the study authors (only for the graph, not the study modal on the map). 

Add a note below the graph: "95% confidence intervals were calculated using the Clopper-Pearson method if not reported in the source."

EDIT: Another idea is to link this to the country modal popup, so for example if you click on Dengue estimates within the Brazil popup, you'd get a popup visualization of the Brazil graph.

![Image](https://github.com/serotracker/dashboard/assets/76851774/f2430288-73ef-4edd-9303-f78cceef9f13)

**Comment by SeanKennyNF** [comment]
Assigning this to myself, I'm doing all of the other 95% CI + visualization stuff so this seems like a pretty natural pickup.
