### ISSUE TITLE
Add a legend to the Serotracker Map

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#22]
The Serotracker map is missing a legend. The legend on the serotracker map should mimic the legend on the Serotracker.com website. 
- The legend should act as a filter for all intents and purposes. 
- Similar to the legend on the arbotracker map, the filter dropdown for the legend values should dissapear when we are on the map and should reappear when we are on the analysis page.

**Comment by SeanKennyNF** [comment]
Resolved as a part of https://github.com/serotracker/dashboard/pull/326
