### ISSUE TITLE
Incorporate what shading means into map legend

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#228]
Similar to SeroTracker, incorporate into the Arboviruses legend

![Image](https://github.com/serotracker/dashboard/assets/76851774/f32772ea-0a1d-4d56-bcc4-8abc6b703d03)

**Comment by HimanshuRanka** [comment]
A small note on this: Since we are moving our current legend into the filters tab, when we add this in it should go in the same place as the map legend has been so far. (Bottom right corner of map)
