### ISSUE TITLE
Update the copy of the about page

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#231]
Pending copy update from @harrietware 

go ahead and update the information on the about page to match the information as provided

**Comment by harrietware** [comment]
General layout:

**Our Data**
[Pending copy]

**Buttons for Our protocol, Submit source, Download CSV**
"Our protocol" links to: https://docs.google.com/document/d/1bdePf81TemPkRqfOKWA4z3-Le0TSbl4BrZ8jTVD5IiE/edit

**Frequently Asked Questions**
[Pending copy]
