### ISSUE TITLE
Define the WHO region acronyms somewhere

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#232]
We need to define the WHO region acronyms somewhere for people who aren't familiar with them. Maybe a note above the visualizations?

AFR: African Region
AMR: Region of the Americas
EMR: Eastern Mediterranean Region
EUR: Region of the Americas
SEAR: South East Asia Region
WPR: Western Pacific Region

**Comment by HimanshuRanka** [comment]
I am thinking we could put an "i" near the filter that gives people the information if they need it. It looks cleaner and is hidden for those who do know what they are?

**Comment by harrietware** [comment]
> I am thinking we could put an "i" near the filter that gives people the information if they need it. It looks cleaner and is hidden for those who do know what they are?

Sounds good to me!
