### ISSUE TITLE
Add a Banner to legacy serotracker about new dashboard

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#233]
We want to add a banner to the top of legacy serotracker right below the header that highlights and emphasizes the launch of the new dashboard as well as links them here

Copy: @harrietware would love a review
JUST LAUNCHED: The team behind SeroTracker has just launched a brand new dashboard focused on Arbovirus studies (or something like this)

**Comment by harrietware** [comment]
Copy looks good to me
