### ISSUE TITLE
Make the Ages table full screen width, update download button to download data

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#247]
We want to make the table full screen (so takes up both rows of the grid) at the very bottom of the page.

We want to make it so that if someone were to download the data it comes out as a single csv file with pathogen as a column
pathogen, whoregion, age 1, age 2
Zika, who1, data age 1, data age 2
Zika, who2, data age 1, data age 2
DENV, who1, data age 1, data age 2 
DENV who2, data age 1, data age 2

And finally we want to add in a way for people to know how many pages there are
currently it is not clear what the next and prev buttons are doing.

**Comment by SeanKennyNF** [comment]
Acknowledging that I see this. Will get on it :)
