### ISSUE TITLE
Add a form to fill out before downloading csv

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#266]
In order to download our complete .csv file using the "Download CSV" button above the data table (or the top of the page), we should first ask to fill out a form indicating their role, affiliation (if relevant), and type of research they’re conducting. This will help us track who is using our data at the start 

SeroTracker example: https://docs.google.com/forms/d/1i59CPaaP5-Ib5Asslkmtb48arhbjY0iwWA92nSW3IIY/edit

**Comment by HimanshuRanka** [comment]
We removed the download csv button and faq question for now, so moving this to planned as we can address it when we enable the button again

**Comment by harrietware** [comment]
Note we got the okay from Thomas to enable the download csv button again and add a suggested citation:
Ware H*, Whelan M*, Ranka H, Roell Y, Aktar S, Kenny S, Pinno E, SeroTracker Research Team, Bobrovitz N**, Arora RK**, Jaenisch T**. ArboTracker: A Dashboard and Data Platform for arbovirus serosurveys (2024); Website, accessible via www.new.SeroTracker.com.    

Maybe we could add a Cite button next to the download csv button which allows the user to copy the text above, as well as adding the citation to the FAQ page?

**Comment by SeanKennyNF** [comment]
Made us a little something over here that we can take a look at https://github.com/serotracker/dashboard/pull/283

**Comment by SeanKennyNF** [comment]
I don't know if we're still interested in a little form form for them to fill out, but if we are, just reach out and I'll see what I can do.
