### ISSUE TITLE
Fix map filter bugs

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#269]
Noticed a couple of bugs when using the Arbovirus checkboxes to filter the map
- Screenshot 1: Only Zika and Dengue selected but the # of estimates clustered show other viruses 
- Screenshot 2: ESM Dengue 2015 selected and map looks good - then ELISA filter applied and # of estimates clustered show other viruses

In both these cases when you zoom in on the clusters, it displays the correct data

![Image](https://github.com/serotracker/dashboard/assets/76851774/54717ac6-2594-4519-b7a5-c025b0255c6a)

![Image](https://github.com/serotracker/dashboard/assets/76851774/ebb465f6-75a9-44a2-941a-8b3de4de7d54)

**Comment by HimanshuRanka** [comment]
Seems to me this has resolved itself, not sure what was happenign but mightve been because of some in progress task.

**Comment by HimanshuRanka** [comment]
Nvm I see it happening on prod, how curious let me take a looksie
