### ISSUE TITLE
Add dashboard tutorial video to dashboard

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#287]
Link somewhere near top of page?

https://drive.google.com/file/d/1cLslLkwI57f2oKI45utkKdOtlW9ZCWpm/view?usp=drive_link

**Comment by SeanKennyNF** [comment]
Hey Harriet!

Sorry for the wait, the entire dev team was sick last week :nauseated_face: 
Please let me know if https://github.com/serotracker/dashboard/pull/289 is what you had in mind. There's a little gif that plays where you can see where the button is. I'm sure we could do something fancier like playing the video in the dashboard if there's interest but this seems like a cute and simple solution for now :)

**Comment by SeanKennyNF** [comment]
Resolved in https://github.com/serotracker/dashboard/pull/297. Closing.
