### ISSUE TITLE
Update GitHub repository data

### ISSUE THREAD

**Issue by harrietware** [serotracker/dashboard#316]
Could we update the data file in the repository below by **May 27th**? We'll need it to run our analysis for the SARS-CoV-2 SRMA update.

https://github.com/serotracker/sars-cov-2-data

**Comment by SeanKennyNF** [comment]
Hey Harriet, yeah not a problem, I can get this updated by then.

**Comment by SeanKennyNF** [comment]
All done! There's a PR open here: https://github.com/serotracker/sars-cov-2-data/pull/2

**Comment by SeanKennyNF** [comment]
This is done now :)
