### ISSUE TITLE
Generate sources for ESM maps

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#5]
Our Arbo Maps need to be underlaid with ESM's

For that we would need to create a map source that combines the current map source we use with an ESM/generate a layer that can be used by mapbox to overlay on the map when certain pathogens are selected

**Comment by harrietware** [comment]
You can write directly to Yannik to ask for the map source
yannik.roell@cuanschutz.edu

**Comment by HimanshuRanka** [comment]
Waiting to recieve the ESM data from Yannik

**Comment by HimanshuRanka** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4493616/
