### ISSUE TITLE
Create Sero Visualizations

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#6]
Create visualizations for the serotracker side of the website. We used nivo for the arbotracker side of things. Consider trying out recharts or another popular and well supported library instead

Main considerations for us are: Stacked Bar graph, Line graph, Area graph, Heat Map (NTH)

Generate 2 visualizations for the serotracker page.

**Comment by harrietware** [comment]
- Lose the Modelled Seroprevalence Globally by WHO Region graph
- Other graphs are good to migrate

**Comment by SeanKennyNF** [comment]
Closing, this was separated into different tickets so there's no need for this one anymore.
