### ISSUE TITLE
Consolidate arbo shortfrom to long form conversion util

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/dashboard#63]
Yeah agreed LMFAO I created one of these too in the visualization files so we will need to consolidate them in the future to ensure consistency. Ok for now

_Originally posted by @HimanshuRanka in https://github.com/PathoTracker/Pathotracker/pull/56#discussion_r1413313165_

**Comment by EliasPinno** [comment]
This ended up being waaaaay more of a task then I expected, and involves a lot of global refactoring we should probably do in one pass. I'm leaving this open but unassigned until we get back to this later.

**Comment by HimanshuRanka** [comment]
Just curious on why we are unable to do this all right now as a part of this ticket? Is there something blocking the task?
