### ISSUE TITLE
Improvements to the "Median seroprevalence by WHO region and age group" graph

### ISSUE THREAD

**Issue by SeanKennyNF** [serotracker/dashboard#82]
The "Median seroprevalence by WHO region and age group" should have a legend or shouldn't be a graph at all and should be in tabular format because we found the graph busy and difficult to read.

**Comment by harrietware** [comment]
Was thinking something like this for the Median seroprevalence by WHO region and age group table where you can switch between pathogens by clicking or scrolling
<img width="620" alt="Screen Shot 2024-03-11 at 3 49 03 PM" src="https://github.com/serotracker/dashboard/assets/76851774/81bef465-d5eb-4df1-a1ec-d3eb931c50b4">

**Comment by harrietware** [comment]
Also can we make sure the cell reads NA when there is no data instead of 0.0%?

**Comment by HimanshuRanka** [comment]
@harrietware do we want it to be completely black and white or would we like to add some form of coloring to the cells for different thresholds (red for 75+ yellow for 25+ and green otherwise with NA being gray?

**Comment by harrietware** [comment]
> @harrietware do we want it to be completely black and white or would we like to add some form of coloring to the cells for different thresholds (red for 75+ yellow for 25+ and green otherwise with NA being gray?

I think some form of coloring would look nice, let's try adding it if not too difficult

**Comment by HimanshuRanka** [comment]
This can be done with the some component that was used to make the data table @SeanKennyNF
