### ISSUE TITLE
Filtering on a WHO region should zoom the map to that WHO region

### ISSUE THREAD

**Issue by SeanKennyNF** [serotracker/dashboard#87]
Very similar to https://github.com/PathoTracker/Pathotracker/issues/18. I would check out https://github.com/PathoTracker/Pathotracker/pull/19 if you want to see what the code to pan the camera to a country looks like because this would be really similar. For the bounding box, you can use google maps to find around the lat and lng of certain places and kind of put the box together yourself by finding coordinates on their map.

**Comment by HimanshuRanka** [comment]
Additionally we want the WHO region and country filters to be in sync. If you select a who region then only countries belonging to that who region are displayed. If you select a set of countries only the who regions in which those countries belong are displayed.
